-- Reverses 0012_vehicle_inspections.sql's own documented "no PDF" decision
-- (Laravel used dompdf; there was no server-side PDF rendering available
-- here at the time). One row per (booking_id, type) already, so one path
-- column is enough - both signatures land on the same row.
alter table vehicle_inspections add column report_pdf_path text;

-- Mirrors 0017_inspection_photo_storage_cross_party_read.sql's shape, for
-- the new documents/inspections/<booking_id>/<type>/report.pdf path
-- convention (type as its own folder segment, not part of the filename, so
-- storage.foldername(name) can address it the same way 0017 addresses
-- inspection_id at segment [3]). The PDF is generated by
-- generate-inspection-report with the service-role key, not under an
-- <uploader_id>/... prefix like the photos/signatures policy it's modeled
-- on - there's no natural "uploader" for a server-generated file. Admin
-- already has blanket documents-bucket access via the existing
-- documents_admin_all policy (0003_storage_policies.sql, is_admin()) - no
-- admin-specific policy needed here.
create policy documents_inspection_report_participant_select on storage.objects
  for select to authenticated
  using (
    bucket_id = 'documents'
    and (storage.foldername(name))[1] = 'inspections'
    and exists (
      select 1 from vehicle_inspections vi
      join bookings b on b.id = vi.booking_id
      where vi.booking_id::text = (storage.foldername(name))[2]
        and vi.type = (storage.foldername(name))[3]
        and (b.renter_id = auth.uid() or is_vendor_owner(b.vendor_id))
    )
  );

-- New admin recipient for the generated report email. Does NOT repoint
-- operations_lead_email (maureen@wopecar.com - a real person, used for
-- vetting-appointment calendar invites, unrelated). Mirrors
-- 0069_vetting_appointment_calendar_sync.sql's insert shape exactly.
insert into app_settings (key, value, description) values
  ('fleet_ops_email', '"fleetops@wopecar.com"'::jsonb, 'Bcc recipient for generated Vehicle Inspection Report PDFs.')
on conflict (key) do nothing;
